### ISSUE TITLE
Basic CLI help text

### ISSUE THREAD

**Issue by Munchotaur** [microsoft/markitdown#43]
As it stands, markitdown installs and works just fine via pipx.

However running it as a command line app with `-h` or `--help` throws an `UnsupportedFormatException`. Not that much help text is needed but it would be better than an error.

**Comment by kevinclb** [comment]
I made a pull request to address this issue as my first contribution to this project.

https://github.com/microsoft/markitdown/pull/46

Let me know if you have any suggestions or comments.

@gagb

**Comment by ArunSunhare** [comment]
Issue Title: Improve Basic CLI Help Text for markitdown
Description:
The markitdown tool installs and runs successfully when installed via pipx. However, when executing the command with --help or without any arguments, the output is unclear or does not provide sufficient guidance to new users.

Steps to Reproduce:
Install markitdown via pipx:
bash
Copy code
pipx install markitdown
Run the command without arguments:
bash
Copy code
markitdown
Alternatively, run the help command:
bash
Copy code
markitdown --help
Observed Behavior:
The output is either unclear, incomplete, or missing critical information about the tool's usage.
Expected Behavior:
The help text should clearly describe:
What the tool does.
How to use it (e.g., syntax and examples).
List of available commands and options.
Proposed Solution:
Update the CLI help text to provide:
A brief description of the tool.
A usage guide, including the command structure.
Examples of common use cases.
Example Help Text:

bash
Copy code
markitdown: A CLI tool for converting markdown files to HTML.

Usage:
  markitdown [OPTIONS] <input_file.md> [output_file.html]

Options:
  --help       Show this help message and exit.
  --version    Display the current version of markitdown.

Examples:
  markitdown input.md output.html
  markitdown input.md

Additional Notes:
Contributors may need to explore the CLI parsing library used (e.g., argparse, click, etc.) to make the necessary improvements.
Ensure the updated help text aligns with any additional features or options provided by markitdown.
